name: CI

on:
  push:
    branches: [ develop, issue-870 ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: Ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt install build-essential gfortran python-numpy python-scipy cython libhdf5-serial-dev python-tables libblas-dev liblapack-dev

    - name: install pyne
      run: |
        python setup.py install --user
        scripts/nuc_data_make